/**
 * rob2.js — the Cochrane RoB 2 instrument for parallel-group randomised trials,
 * "effect of ASSIGNMENT to intervention" (intention-to-treat) variant.
 *
 * PURE: data + deterministic algorithm. No Prisma / Express / React / network /
 * randomness / Date.now(). Same input → same output (this is what makes it
 * testable and citable).
 *
 * The exported `ROB2` object is JSON-SERIALISABLE instrument DATA (domains,
 * signalling questions, response options, guidance, declarative branching) so
 * `GET /api/rob/instruments/rob2` can ship it to a data-driven UI. The judgement
 * ALGORITHMS are exported as separate pure functions (`judgeDomain`,
 * `judgeOverall`) which the generic engine (engine.js) calls.
 *
 * SOURCE OF THE ALGORITHM (see src/research-engine/docs/rob-validation.md):
 *   - Sterne et al., RoB 2 guidance. Domain 1 (Table 4, randomisation) and the
 *     Overall roll-up (Table 1) are encoded VERBATIM from the official guidance
 *     decision tables. Domains 2–5 encode the CURRENT (22 Aug 2019) RoB 2 tool
 *     algorithm whose signalling-question structure (2.1–2.7, 3.1–3.4, 4.1–4.5,
 *     5.1–5.3) the build spec and the live riskofbias.info Excel tool use.
 *   - Every branch is covered by a golden test in tests/unit/rob2-*.test.js.
 *
 * The engine COMPUTES the proposed judgement and returns a human-readable
 * `reasons` trace; the human decides and may override with a logged rationale.
 */

// ── Response + judgement vocabularies ────────────────────────────────────────
export const RESPONSES = ['Y', 'PY', 'PN', 'N', 'NI', 'NA'];
export const RESPONSE_LABELS = {
  Y: 'Yes',
  PY: 'Probably yes',
  PN: 'Probably no',
  N: 'No',
  NI: 'No information',
  NA: 'Not applicable',
};
export const JUDGMENTS = ['low', 'some', 'high'];
export const JUDGMENT_LABELS = {
  low: 'Low risk of bias',
  some: 'Some concerns',
  high: 'High risk of bias',
};

// ── Response-class helpers (the algorithm only cares about these classes) ─────
const yp = r => r === 'Y' || r === 'PY';   // "Yes / Probably yes"
const np = r => r === 'N' || r === 'PN';   // "No / Probably no"
const ni = r => r === 'NI';                // "No information"

/** Coerce a stored answer to a bare response code (string) or undefined. */
function code(answers, qid) {
  const v = answers ? answers[qid] : undefined;
  if (v == null) return undefined;
  // Accept either a bare code ('Y') or an object { response: 'Y' }.
  return typeof v === 'string' ? v : v.response;
}

// ── Instrument DATA (serialisable) ───────────────────────────────────────────
// Each question's `branch` is a declarative reachability rule the generic engine
// interprets (null = always shown). Rule shape:
//   { allOf: [{ q, in:[...] }], anyOf: [{ q, in:[...] }] }
// A question is reachable when every allOf condition holds AND at least one anyOf
// condition holds (each clause optional).

const YPNI = ['Y', 'PY', 'NI'];
const NPNI = ['N', 'PN', 'NI'];
const YP = ['Y', 'PY'];

const DOMAINS = [
  {
    id: 'D1',
    name: 'Bias arising from the randomisation process',
    shortLabel: 'Randomisation',
    description:
      'Whether the allocation sequence was random and concealed, and whether baseline imbalances suggest a problem.',
    questions: [
      {
        id: '1.1',
        text: 'Was the allocation sequence random?',
        guidance:
          'Answer “Yes/Probably yes” for sequences generated by a truly random or otherwise unpredictable process (computer random-number generator, random-number table, etc.).',
        branch: null,
      },
      {
        id: '1.2',
        text: 'Was the allocation sequence concealed until participants were enrolled and assigned to interventions?',
        guidance:
          'Allocation concealment prevents foreknowledge of upcoming assignments (central randomisation, sequentially numbered opaque sealed envelopes, etc.).',
        branch: null,
      },
      {
        id: '1.3',
        text: 'Did baseline differences between intervention groups suggest a problem with the randomisation process?',
        guidance:
          'Consider whether observed baseline imbalances are larger than expected by chance. This answer must not influence 1.1 or 1.2.',
        branch: null,
      },
    ],
  },
  {
    id: 'D2',
    name: 'Bias due to deviations from intended interventions (effect of assignment to intervention)',
    shortLabel: 'Deviations',
    description:
      'Whether there were deviations from intended interventions arising from the trial context, and whether an appropriate (ITT-style) analysis was used.',
    questions: [
      {
        id: '2.1',
        text: 'Were participants aware of their assigned intervention during the trial?',
        guidance: 'Awareness (lack of blinding) of participants of their assigned group.',
        branch: null,
      },
      {
        id: '2.2',
        text: "Were carers and people delivering the interventions aware of participants' assigned intervention during the trial?",
        guidance: 'Awareness (lack of blinding) of carers and intervention providers.',
        branch: null,
      },
      {
        id: '2.3',
        text: 'Were there deviations from the intended intervention that arose because of the trial context?',
        guidance:
          'Only deviations that arose BECAUSE OF the trial context (would not occur outside the trial) are relevant to the effect of assignment.',
        branch: { anyOf: [{ q: '2.1', in: YPNI }, { q: '2.2', in: YPNI }] },
      },
      {
        id: '2.4',
        text: 'Were these deviations likely to have affected the outcome?',
        guidance: 'Judge whether the trial-context deviations were substantial enough to affect the outcome.',
        branch: { allOf: [{ q: '2.3', in: YP }] },
      },
      {
        id: '2.5',
        text: 'Were these deviations from intended intervention balanced between groups?',
        guidance: 'Balanced (similar) deviations across groups are of less concern than imbalanced ones.',
        branch: { allOf: [{ q: '2.4', in: YPNI }] },
      },
      {
        id: '2.6',
        text: 'Was an appropriate analysis used to estimate the effect of assignment to intervention?',
        guidance:
          'An appropriate analysis is intention-to-treat (ITT) or modified ITT, analysing participants in their randomised groups.',
        branch: null,
      },
      {
        id: '2.7',
        text: 'Was there potential for a substantial impact (on the result) of the failure to analyse participants in the group to which they were randomised?',
        guidance: 'Only asked when the analysis was not (clearly) appropriate.',
        branch: { allOf: [{ q: '2.6', in: NPNI }] },
      },
    ],
  },
  {
    id: 'D3',
    name: 'Bias due to missing outcome data',
    shortLabel: 'Missing data',
    description:
      'Whether outcome data were available for nearly all participants, and—if not—whether the result is likely biased by the missingness.',
    questions: [
      {
        id: '3.1',
        text: 'Were data for this outcome available for all, or nearly all, participants randomised?',
        guidance:
          '“Nearly all” means enough to be confident of the findings. Imputed data count as missing, not as available outcome data.',
        branch: null,
      },
      {
        id: '3.2',
        text: 'Is there evidence that the result was not biased by missing outcome data?',
        guidance:
          'Evidence may come from appropriate analysis methods and/or sensitivity analyses showing robustness to the missing data.',
        branch: { allOf: [{ q: '3.1', in: NPNI }] },
      },
      {
        id: '3.3',
        text: 'Could missingness in the outcome depend on its true value?',
        guidance: 'Consider whether the reasons for missingness are likely related to the true (unobserved) outcome value.',
        branch: { allOf: [{ q: '3.2', in: NPNI }] },
      },
      {
        id: '3.4',
        text: 'Is it likely that missingness in the outcome depended on its true value?',
        guidance: 'Distinguishes “could depend” (3.3) from “likely depended”.',
        branch: { allOf: [{ q: '3.3', in: YPNI }] },
      },
    ],
  },
  {
    id: 'D4',
    name: 'Bias in measurement of the outcome',
    shortLabel: 'Measurement',
    description:
      'Whether the outcome measurement method was appropriate and comparable between groups, and whether assessor awareness could have influenced it.',
    questions: [
      {
        id: '4.1',
        text: 'Was the method of measuring the outcome inappropriate?',
        guidance: 'An inappropriate or insensitive measurement method is itself a source of bias.',
        branch: null,
      },
      {
        id: '4.2',
        text: 'Could measurement or ascertainment of the outcome have differed between intervention groups?',
        guidance: 'Different methods, timings or intensities of outcome ascertainment between groups.',
        branch: null,
      },
      {
        id: '4.3',
        text: 'Were outcome assessors aware of the intervention received by study participants?',
        guidance:
          'For participant-reported outcomes the assessor is the participant. Only asked when measurement was appropriate and comparable.',
        branch: { allOf: [{ q: '4.1', in: NPNI }, { q: '4.2', in: NPNI }] },
      },
      {
        id: '4.4',
        text: 'Could assessment of the outcome have been influenced by knowledge of intervention received?',
        guidance: 'Subjective / judgement-based outcomes are more susceptible than objective ones (e.g. all-cause mortality).',
        branch: { allOf: [{ q: '4.3', in: YPNI }] },
      },
      {
        id: '4.5',
        text: 'Is it likely that assessment of the outcome was influenced by knowledge of intervention received?',
        guidance: 'Distinguishes “could be influenced” (4.4) from “likely was influenced”.',
        branch: { allOf: [{ q: '4.4', in: YPNI }] },
      },
    ],
  },
  {
    id: 'D5',
    name: 'Bias in selection of the reported result',
    shortLabel: 'Selective reporting',
    description:
      'Whether the reported result was analysed per a pre-specified plan, or likely selected from multiple measurements or analyses on the basis of the results.',
    questions: [
      {
        id: '5.1',
        text: 'Were the data that produced this result analysed in accordance with a pre-specified analysis plan that was finalised before unblinded outcome data were available for analysis?',
        guidance: 'A protocol or statistical analysis plan finalised before unblinded data were available.',
        branch: null,
      },
      {
        id: '5.2',
        text: 'Is the numerical result being assessed likely to have been selected, on the basis of the results, from multiple eligible outcome measurements (e.g. scales, definitions, time points) within the outcome domain?',
        guidance: 'Selection among multiple MEASUREMENTS (scales, definitions, time points) on the basis of the results.',
        branch: null,
      },
      {
        id: '5.3',
        text: 'Is the numerical result being assessed likely to have been selected, on the basis of the results, from multiple eligible analyses of the data?',
        guidance: 'Selection among multiple ANALYSES (adjusted/unadjusted, subgroups, transformations) on the basis of the results.',
        branch: null,
      },
    ],
  },
];

export const ROB2 = Object.freeze({
  id: 'RoB2',
  name: 'Cochrane Risk of Bias 2 (RoB 2)',
  instrumentVersion: '2019-08-22',
  variant: 'assignment',
  variantLabel: 'Effect of assignment to intervention (intention-to-treat)',
  design: 'parallel-group',
  responseOptions: RESPONSES.filter(r => r !== 'NA').map(value => ({ value, label: RESPONSE_LABELS[value] })),
  judgmentLevels: JUDGMENTS.map(value => ({ value, label: JUDGMENT_LABELS[value] })),
  domains: DOMAINS.map(d => Object.freeze({
    ...d,
    questions: d.questions.map(q => Object.freeze({ ...q })),
  })),
  overallGuidance:
    'Low when every domain is Low; Some concerns when at least one domain is Some concerns and none is High; High when at least one domain is High. Some concerns in multiple domains may be considered additive and escalated to High with a logged rationale.',
});

// ── Per-domain judgement algorithms (pure) ───────────────────────────────────
// Each returns { judgment, reasons: string[] }. `reasons` is the transparent
// "why this judgement" trace the UI shows. Unanswered reachable questions are
// treated conservatively (they cannot push a domain to Low); completeness is
// reported separately by the engine so a proposal is never silently "complete".

function domain1(a) {
  const q11 = code(a, '1.1'), q12 = code(a, '1.2'), q13 = code(a, '1.3');
  const reasons = [];
  // Encodes the official RoB 2 Table 4 (randomisation) exactly. Concealment (1.2)
  // is the dominant driver; baseline-imbalance signal (1.3) escalates.
  if (np(q12)) {
    reasons.push('Allocation sequence was not concealed (1.2 = No/Probably no).');
    return { judgment: 'high', reasons };
  }
  if (yp(q13)) {
    if (yp(q12)) {
      reasons.push('Allocation was concealed (1.2) but baseline differences suggest a randomisation problem (1.3 = Yes/Probably yes).');
      reasons.push('Substantial imbalance despite sound methods warrants careful review; default is Some concerns.');
      return { judgment: 'some', reasons };
    }
    reasons.push('No information on allocation concealment (1.2 = NI) and baseline differences suggest a randomisation problem (1.3 = Yes/Probably yes).');
    return { judgment: 'high', reasons };
  }
  if (yp(q12)) {
    if (np(q11)) {
      reasons.push('Allocation was concealed (1.2) with no baseline-imbalance signal, but the sequence was not random (1.1 = No/Probably no).');
      return { judgment: 'some', reasons };
    }
    reasons.push('Allocation sequence was random or unknown (1.1) AND concealed (1.2), with no baseline-imbalance signal (1.3).');
    return { judgment: 'low', reasons };
  }
  reasons.push('No information on allocation concealment (1.2 = NI) and no baseline-imbalance signal (1.3).');
  return { judgment: 'some', reasons };
}

function domain2(a) {
  const q21 = code(a, '2.1'), q22 = code(a, '2.2'), q23 = code(a, '2.3');
  const q24 = code(a, '2.4'), q25 = code(a, '2.5'), q26 = code(a, '2.6'), q27 = code(a, '2.7');
  const reasons = [];

  // Part A — deviations from intended intervention arising from the trial context.
  // Official: once deviations AROSE from the trial context (2.3 Y/PY) the domain
  // can no longer be Low — Low requires either no awareness (2.1 & 2.2 N/PN) or no
  // such deviations (2.3 N/PN). 2.3 Y/PY & 2.4 N/PN is Some concerns (not Low).
  let devPart;
  if (np(q21) && np(q22)) {
    devPart = 'low';
    reasons.push('Participants, carers and personnel were unaware of the assigned intervention (2.1 & 2.2 = No/Probably no).');
  } else if (np(q23)) {
    devPart = 'low';
    reasons.push('There were no deviations from the intended intervention arising from the trial context (2.3 = No/Probably no).');
  } else if (yp(q23) && yp(q24) && np(q25)) {
    devPart = 'high';
    reasons.push('Trial-context deviations likely affected the outcome (2.3 & 2.4 = Yes/Probably yes) and were imbalanced between groups (2.5 = No/Probably no).');
  } else if (yp(q23)) {
    devPart = 'some';
    reasons.push('Deviations arose from the trial context (2.3 = Yes/Probably yes), so the domain cannot be Low, but they were not clearly both outcome-affecting and imbalanced.');
  } else {
    devPart = 'some';
    reasons.push('There is insufficient information about deviations arising from the trial context (2.3 = NI / unanswered).');
  }

  // Part B — appropriateness of the analysis (ITT). Official: an inappropriate
  // analysis is NEVER Low — its best is Some concerns (2.7 N/PN). 2.7 = Y/PY/NI
  // (substantial impact, or no information about it) → High. Only an explicitly
  // appropriate analysis (2.6 Y/PY) is Low.
  let anaPart;
  if (yp(q26)) {
    anaPart = 'low';
    reasons.push('An appropriate (intention-to-treat) analysis was used to estimate the effect of assignment (2.6 = Yes/Probably yes).');
  } else if (np(q27)) {
    anaPart = 'some';
    reasons.push('The analysis was not appropriate, but the failure to analyse as randomised had little potential for substantial impact (2.7 = No/Probably no) — an inappropriate analysis cannot be Low risk.');
  } else if (yp(q27) || ni(q27)) {
    anaPart = 'high';
    reasons.push('The analysis was not appropriate and the failure to analyse as randomised had (or may have had — no information) a substantial impact on the result (2.6 = No/Probably no/NI AND 2.7 = Yes/Probably yes/NI).');
  } else {
    anaPart = 'some';
    reasons.push('Appropriateness of the analysis is not yet established (2.6 / 2.7 unanswered).');
  }

  return { judgment: worst(devPart, anaPart), reasons };
}

function domain3(a) {
  const q31 = code(a, '3.1'), q32 = code(a, '3.2'), q33 = code(a, '3.3'), q34 = code(a, '3.4');
  const reasons = [];
  if (yp(q31)) {
    reasons.push('Outcome data were available for all, or nearly all, randomised participants (3.1 = Yes/Probably yes).');
    return { judgment: 'low', reasons };
  }
  if (yp(q32)) {
    reasons.push('There is evidence the result was not biased by the missing outcome data (3.2 = Yes/Probably yes).');
    return { judgment: 'low', reasons };
  }
  if (np(q33)) {
    reasons.push('Missingness in the outcome could not depend on its true value (3.3 = No/Probably no).');
    return { judgment: 'low', reasons };
  }
  // Official: 3.4 = Y/PY/NI → High (no information about whether missingness
  // likely depended on the true value cannot be ruled out → conservatively High).
  // Only an explicit 3.4 = N/PN → Some concerns.
  if (yp(q34) || ni(q34)) {
    reasons.push('Missingness could depend on the true value and it likely did, or there is no information that it did not (3.4 = Yes/Probably yes/NI).');
    return { judgment: 'high', reasons };
  }
  if (np(q34)) {
    reasons.push('Missingness could depend on the true value but is unlikely to have done so (3.4 = No/Probably no).');
    return { judgment: 'some', reasons };
  }
  reasons.push('Missingness could depend on the true value; whether it likely did is not yet established (3.4 unanswered).');
  return { judgment: 'some', reasons };
}

function domain4(a) {
  const q41 = code(a, '4.1'), q42 = code(a, '4.2'), q43 = code(a, '4.3'), q44 = code(a, '4.4'), q45 = code(a, '4.5');
  const reasons = [];
  if (yp(q41) || yp(q42)) {
    if (yp(q41)) reasons.push('The method of measuring the outcome was inappropriate (4.1 = Yes/Probably yes).');
    if (yp(q42)) reasons.push('Measurement/ascertainment of the outcome could have differed between groups (4.2 = Yes/Probably yes).');
    return { judgment: 'high', reasons };
  }
  // 4.5 (likely influenced) is only reachable via 4.4 = Y/PY/NI. Official: an
  // ANSWERED 4.5 of Y/PY/NI → High (no information about likely influence cannot
  // be ruled out). An unanswered 4.5 does not escalate (provisional).
  if (yp(q45) || ni(q45)) {
    reasons.push('Assessment of the outcome was likely influenced by knowledge of the intervention received, or there is no information that it was not (4.5 = Yes/Probably yes/NI).');
    return { judgment: 'high', reasons };
  }
  // Official Low allows 4.1 = N/PN/NI (no info on appropriateness gets the benefit
  // of the doubt) but REQUIRES 4.2 = N/PN (an NI on between-group difference blocks
  // Low), plus assessors blinded (4.3 N/PN) or knowledge could not influence (4.4 N/PN).
  if ((np(q41) || ni(q41)) && np(q42) && (np(q43) || np(q44))) {
    if (np(q43)) reasons.push('Outcome assessors were unaware of the intervention received (4.3 = No/Probably no); measurement was appropriate and comparable.');
    else reasons.push('Assessment could not have been influenced by knowledge of the intervention (4.4 = No/Probably no); measurement was appropriate and comparable.');
    return { judgment: 'low', reasons };
  }
  reasons.push('Outcome assessors may have been aware of the intervention and influence on assessment is possible but not clearly likely (some concerns).');
  return { judgment: 'some', reasons };
}

function domain5(a) {
  const q51 = code(a, '5.1'), q52 = code(a, '5.2'), q53 = code(a, '5.3');
  const reasons = [];
  if (yp(q52) || yp(q53)) {
    if (yp(q52)) reasons.push('The result was likely selected from multiple eligible outcome measurements on the basis of the results (5.2 = Yes/Probably yes).');
    if (yp(q53)) reasons.push('The result was likely selected from multiple eligible analyses on the basis of the results (5.3 = Yes/Probably yes).');
    return { judgment: 'high', reasons };
  }
  if (yp(q51) && np(q52) && np(q53)) {
    reasons.push('Analysis followed a pre-specified plan (5.1 = Yes/Probably yes) with no evidence of selection from multiple measurements or analyses (5.2 & 5.3 = No/Probably no).');
    return { judgment: 'low', reasons };
  }
  reasons.push('No clear evidence of result-driven selection, but the pre-specified plan or selection status is uncertain (some concerns).');
  return { judgment: 'some', reasons };
}

const DOMAIN_ALGORITHMS = {
  D1: domain1, D2: domain2, D3: domain3, D4: domain4, D5: domain5,
};

/** Severity order for combining judgements. */
const RANK = { low: 0, some: 1, high: 2 };
function worst(a, b) {
  return RANK[a] >= RANK[b] ? a : b;
}

/**
 * Propose a domain judgement from the answers (pure).
 * @returns {{ judgment: 'low'|'some'|'high', reasons: string[] }}
 */
export function judgeDomain(domainId, answers) {
  const fn = DOMAIN_ALGORITHMS[domainId];
  if (!fn) throw new Error(`Unknown RoB 2 domain: ${domainId}`);
  return fn(answers || {});
}

/**
 * Propose the overall judgement from the five domain judgements (pure).
 * Encodes the official Table 1 roll-up: any High → High; else any Some → Some;
 * else Low. When ≥2 domains are Some concerns, sets multiSomeConcernsFlag so the
 * UI can offer a non-blocking escalation to High (with a logged rationale).
 * @param {Record<string,'low'|'some'|'high'>|Array} domainJudgments
 */
export function judgeOverall(domainJudgments) {
  const values = Array.isArray(domainJudgments)
    ? domainJudgments.map(d => (typeof d === 'string' ? d : d.judgment))
    : Object.values(domainJudgments || {}).map(d => (typeof d === 'string' ? d : d.judgment));

  const highs = values.filter(v => v === 'high').length;
  const somes = values.filter(v => v === 'some').length;
  const reasons = [];
  let judgment;
  if (highs > 0) {
    judgment = 'high';
    reasons.push(`At least one domain is at High risk of bias (${highs} of ${values.length}).`);
  } else if (somes > 0) {
    judgment = 'some';
    reasons.push(`No domain is High; at least one domain raises Some concerns (${somes} of ${values.length}).`);
  } else {
    judgment = 'low';
    reasons.push('Every domain is judged at Low risk of bias.');
  }
  const multiSomeConcernsFlag = judgment === 'some' && somes >= 2;
  if (multiSomeConcernsFlag) {
    reasons.push('Multiple domains raise Some concerns — consider whether these are additive and warrant escalation to High (with a logged rationale).');
  }
  return { judgment, reasons, multiSomeConcernsFlag };
}

export { code as _answerCode, yp as _yp, np as _np, ni as _ni };
