/**
 * ExportTab.jsx — export screening data (97.md Phase 2 + prompt9 Task 6).
 *
 * Headline action: "Download screening file (ZIP)" — a single portable archive
 * (CSV + RIS + JSON backup + README) generated by the durable async export job
 * (format 'zip'; the server streams it off the request thread and this tab polls
 * exactly like the over-cap CSV path). Partial-format failures surface as a
 * NON-blocking warning banner (the ZIP is still complete apart from the named
 * optional file).
 *
 * The original per-format export (CSV / JSON / RIS through the shared
 * ExportDialog, sync → 413 → async fallback) is retained below unchanged.
 */
import { useState, useEffect, useCallback, useRef } from 'react';
import { C, MONO } from '../ui/theme.js';
import { Loading, ErrorBanner, Button, StatTile, Card } from '../ui/components.jsx';
import { screeningApi } from '../api-client/screeningApi.js';
import ExportDialog from '../../components/ExportDialog.jsx';
import { downloadBlob } from '../../components/exportCore.js';

const FILTERS = [
  { key: 'all',      label: 'All records',  desc: 'Every record in the project' },
  { key: 'include',  label: 'Included',     desc: 'Records you marked include' },
  { key: 'exclude',  label: 'Excluded',     desc: 'Records you marked exclude' },
  { key: 'maybe',    label: 'Maybe',        desc: 'Records you marked maybe' },
];

// Only the formats the server's export endpoint accepts for decisions.
const FORMATS = [
  { id: 'csv',  label: 'CSV' },
  { id: 'json', label: 'JSON' },
  { id: 'ris',  label: 'RIS' },
];

// Researcher-facing explanation of what lives inside the screening file (97.md:
// clear format categories, no internal jargon, no universal-compatibility claim —
// named example applications only, never "any spreadsheet tool").
export const ZIP_CONTENTS = [
  { name: 'References and decisions (CSV)', desc: 'A human-readable spreadsheet of every reference with its screening decisions, exclusion reasons, notes and reviewer decisions. Opens in spreadsheet applications such as Excel, Google Sheets or LibreOffice Calc.' },
  { name: 'References (RIS)', desc: 'Citation data for reference managers such as Zotero, EndNote or Mendeley. Citations only — screening decisions stay in the CSV and JSON files.' },
  { name: 'Complete screening backup (JSON)', desc: 'The full structured PecanRev backup of this project’s screening data, for safekeeping or a future restore.' },
];

// Shown when the job reports warningCount > 0 but the warning texts themselves
// were lost (e.g. an unparseable stored payload) — the banner must never be
// silently suppressed while the archive is missing an optional file.
export const GENERIC_ZIP_WARNING =
  'One or more optional files could not be generated. See EXPORT-WARNINGS.txt inside the ZIP for details.';

/**
 * ZipExportCard — the presentational "Download screening file (ZIP)" card
 * (97.md Phase 2 headline surface). Pure props → markup, exported so unit tests
 * can SSR-render every state (idle / empty / running / completed / warnings)
 * without a DOM or network.
 */
export function ZipExportCard({
  empty = false, running = false, progress = '', error = null,
  warnings = [], warningCount = 0, note = '', downloadUrl = '', filename = '',
  onDownload,
}) {
  const shownWarnings = (warnings && warnings.length) ? warnings
    : warningCount > 0 ? [GENERIC_ZIP_WARNING] : [];
  return (
    <Card style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 11, color: C.muted, fontFamily: MONO, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 10 }}>
        Download screening file
      </div>
      <div style={{ fontSize: 12.5, color: C.txt2, lineHeight: 1.55, marginBottom: 10 }}>
        One ZIP file with this project&rsquo;s references and screening decisions, ready to use outside PecanRev:
      </div>
      <ul style={{ margin: '0 0 12px', paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 6 }}>
        {ZIP_CONTENTS.map(f => (
          <li key={f.name} style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>
            <strong style={{ color: C.txt2, fontWeight: 600 }}>{f.name}</strong> — {f.desc}
          </li>
        ))}
      </ul>
      <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5, marginBottom: 12 }}>
        A README inside the file explains each format. Not every third-party application can
        preserve every PecanRev-specific field — the CSV and JSON files keep the complete
        screening detail.
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
        <Button onClick={onDownload} disabled={empty || running}>
          {running ? 'Preparing…' : '↓ Download screening file (ZIP)'}
        </Button>
        {running && (
          <span role="status" aria-live="polite" style={{ fontSize: 12, color: C.txt2 }}>{progress}</span>
        )}
        {empty && <span style={{ fontSize: 12, color: C.muted }}>Import records before exporting.</span>}
        {note && <span role="status" style={{ fontSize: 12, color: C.grn }}>{note}</span>}
        {!running && downloadUrl && (
          <a href={downloadUrl} download={filename || true} style={{ fontSize: 12, color: C.acc }}>
            Download again
          </a>
        )}
      </div>
      {error && (
        <div role="alert" style={{ marginTop: 10, fontSize: 12.5, color: C.red, lineHeight: 1.5 }}>
          {error}
        </div>
      )}
      {shownWarnings.length > 0 && (
        <div role="status" style={{
          marginTop: 12, padding: '10px 12px', borderRadius: 8,
          border: `1px solid ${C.ylw}`, background: 'rgba(230, 180, 60, 0.08)',
          fontSize: 12, color: C.txt2, lineHeight: 1.55,
        }}>
          <strong style={{ fontWeight: 600 }}>Your download finished with a warning.</strong>
          <ul style={{ margin: '6px 0 0', paddingLeft: 16 }}>
            {shownWarnings.map((w, i) => <li key={i}>{w}</li>)}
          </ul>
          <div style={{ marginTop: 6, color: C.muted }}>
            The other files in the ZIP are complete — see EXPORT-WARNINGS.txt inside the file.
          </div>
        </div>
      )}
    </Card>
  );
}

export default function ExportTab({ pid }) {
  const [stats, setStats]   = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]   = useState(null);
  const [filter, setFilter] = useState('all');
  const [note, setNote]     = useState('');
  const [expItem, setExpItem] = useState(null);
  // 97.md — ZIP job state (running flag, live progress text, completion warnings,
  // completion note + a persistent re-download link for the finished archive).
  const [zipRunning, setZipRunning]   = useState(false);
  const [zipProgress, setZipProgress] = useState('');
  const [zipWarnings, setZipWarnings] = useState([]);
  const [zipWarningCount, setZipWarningCount] = useState(0);
  const [zipError, setZipError]       = useState(null);
  const [zipNote, setZipNote]         = useState('');
  const [zipDone, setZipDone]         = useState(null); // { url, filename }
  // 62.md rec round: stop the async-export poll loop if the tab unmounts (navigating away
  // shouldn't leave a 12-minute background polling loop running). The effect body must
  // re-arm the ref: under React 18 StrictMode's dev double-invoke (setup → cleanup →
  // setup) a cleanup-only effect leaves the ref permanently false, which silently
  // killed the ZIP poll loop at its first iteration.
  const mountedRef = useRef(true);
  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  const load = useCallback(async () => {
    setError(null);
    try { setStats(await screeningApi.getStats(pid)); }
    catch (e) { setError(e.message || 'Failed to load stats'); }
    finally { setLoading(false); }
  }, [pid]);
  useEffect(() => { load(); }, [load]);

  const countFor = (k) => !stats ? 0 : k === 'all' ? stats.total : k === 'include' ? stats.included : k === 'exclude' ? stats.excluded : stats.maybe;

  // ── 97.md — the portable screening file (always an async job) ──────────────
  async function downloadScreeningFile() {
    setZipRunning(true);
    setZipProgress('Starting export…');
    setZipWarnings([]);
    setZipWarningCount(0);
    setZipError(null);
    setZipNote('');
    setZipDone(null);
    try {
      const started = await screeningApi.startExport(pid, { format: 'zip' });
      const jobId = started.jobId;
      for (let i = 0; i < 600; i++) { // ~12 min ceiling at 1.2s/poll
        if (!mountedRef.current) return; // tab unmounted → stop polling (job continues server-side)
        const st = await screeningApi.getExportJob(pid, jobId);
        if (st.status === 'failed') throw new Error(st.error || 'The export failed. Please try again.');
        if (st.ready) {
          // Same-origin anchor streams the file natively (no blob in memory);
          // the download route re-checks permission.
          const url = screeningApi.exportDownloadUrl(pid, jobId);
          const a = document.createElement('a');
          a.href = url;
          a.download = st.filename || '';
          document.body.appendChild(a); a.click(); a.remove();
          setZipRunning(false);
          setZipProgress('');
          // Non-blocking partial-failure surface: keep the count alongside the
          // texts so the banner still shows (generically) if the texts are lost.
          setZipWarnings(Array.isArray(st.warnings) ? st.warnings : []);
          setZipWarningCount(st.warningCount ?? 0);
          setZipDone({ url, filename: st.filename || '' });
          setZipNote('Download started.'); setTimeout(() => { if (mountedRef.current) setZipNote(''); }, 3000);
          return;
        }
        setZipProgress(`Preparing your screening file…${st.progress != null ? ` (${st.progress}%)` : ''}`);
        await new Promise(r => setTimeout(r, 1200));
      }
      throw new Error('The export is taking longer than expected — please check back shortly.');
    } catch (e) {
      if (!mountedRef.current) return;
      setZipRunning(false);
      setZipProgress('');
      setZipError(e.message || 'The export failed. Please try again.');
    }
  }

  function openExport() {
    const chosenFilter = filter; // freeze the filter the dialog exports with
    setExpItem({
      id: 'sift-decisions',
      title: 'Screening decisions',
      formats: FORMATS,
      sizing: false,
      defaults: { format: 'csv' },
      run: async ({ format }, onProgress) => {
        // 62.md — try the fast synchronous path (instant for typical projects). If the
        // project is too large the server answers 413; we then switch to a durable async
        // export job, show progress, and download the finished file — so a big project
        // never 504s or freezes the browser.
        let res;
        try { res = await fetch(screeningApi.exportUrl(pid, { format, filter: chosenFilter }), { credentials: 'include' }); }
        catch { throw new Error('Network error while exporting. Please try again.'); }

        if (res.ok) {
          downloadBlob(await res.blob(), `sift-export-${String(pid).slice(0, 8)}.${format}`);
          setNote('Download started.'); setTimeout(() => setNote(''), 3000);
          return;
        }
        if (res.status !== 413) {
          let msg = `Export failed (${res.status}).`;
          try { const d = await res.json(); if (d?.error) msg = d.error; } catch { /* keep default */ }
          throw new Error(msg);
        }

        // Large project → async export job (start → poll → download).
        onProgress?.('Preparing export…');
        const started = await screeningApi.startExport(pid, { format, filter: chosenFilter });
        const jobId = started.jobId;
        for (let i = 0; i < 600; i++) { // ~12 min ceiling at 1.2s/poll
          if (!mountedRef.current) return; // tab unmounted → stop polling (job continues server-side)
          const st = await screeningApi.getExportJob(pid, jobId);
          if (st.status === 'failed') throw new Error(st.error || 'Export failed.');
          if (st.ready) {
            // The file exists + the download route re-checks permission; a same-origin
            // anchor streams it natively (no blob in memory).
            const a = document.createElement('a');
            a.href = screeningApi.exportDownloadUrl(pid, jobId);
            a.download = st.filename || '';
            document.body.appendChild(a); a.click(); a.remove();
            setNote('Download started.'); setTimeout(() => setNote(''), 3000);
            return;
          }
          onProgress?.(`Preparing export…${st.progress != null ? ` (${st.progress}%)` : ''}`);
          await new Promise(r => setTimeout(r, 1200));
        }
        throw new Error('Export is taking longer than expected; please check back shortly.');
      },
    });
  }

  if (loading) return <Loading label="Loading export…" />;

  const empty = !stats || stats.total === 0;

  return (
    <div style={{ maxWidth: 680 }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 16px' }}>Export screening data</h2>
      {error && <ErrorBanner onRetry={load}>{error}</ErrorBanner>}

      {stats && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))', gap: 10, marginBottom: 22 }}>
          <StatTile label="Total"     value={stats.total}     color={C.txt2} />
          <StatTile label="Included"  value={stats.included}  color={C.grn} />
          <StatTile label="Excluded"  value={stats.excluded}  color={C.red} />
          <StatTile label="Maybe"     value={stats.maybe}     color={C.ylw} />
          <StatTile label="Undecided" value={stats.undecided} color={C.muted} />
        </div>
      )}

      {/* ── 97.md headline action: the portable screening file ─────────────── */}
      <ZipExportCard
        empty={empty}
        running={zipRunning}
        progress={zipProgress}
        error={zipError}
        warnings={zipWarnings}
        warningCount={zipWarningCount}
        note={zipNote}
        downloadUrl={zipDone?.url || ''}
        filename={zipDone?.filename || ''}
        onDownload={downloadScreeningFile}
      />

      {/* ── Single-format export (unchanged flow) ──────────────────────────── */}
      <Card style={{ marginBottom: 16 }}>
        <div style={{ fontSize: 11, color: C.muted, fontFamily: MONO, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 12 }}>
          Export a single format
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {FILTERS.map(f => (
            <label key={f.key} style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer', padding: '8px 10px', borderRadius: 7, border: `1px solid ${filter === f.key ? C.acc2 : C.brd}`, background: filter === f.key ? C.accBg : 'transparent' }}>
              <input type="radio" checked={filter === f.key} onChange={() => setFilter(f.key)} style={{ accentColor: C.acc }} />
              <span style={{ flex: 1 }}>
                <span style={{ fontSize: 13, color: C.txt }}>{f.label}</span>
                <span style={{ fontSize: 11, color: C.muted, marginLeft: 8 }}>{f.desc}</span>
              </span>
              <span style={{ fontSize: 12, fontFamily: MONO, color: C.txt2 }}>{countFor(f.key)}</span>
            </label>
          ))}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginTop: 12 }}>
          <Button onClick={openExport} disabled={countFor(filter) === 0}>↓ Export…</Button>
          <span style={{ fontSize: 12, color: C.muted }}>{countFor(filter)} records selected · choose CSV, JSON or RIS</span>
          {note && <span style={{ fontSize: 12, color: C.grn }}>{note}</span>}
        </div>
      </Card>

      {/* 65.md SCR-2 — what the CSV/JSON export now carries (columns are append-only). */}
      <div style={{ marginTop: 14, fontSize: 11.5, color: C.muted, lineHeight: 1.6, maxWidth: 640 }}>
        CSV/JSON exports include the record metadata, <strong style={{ color: C.txt2 }}>your</strong> decision with its
        timestamp, per-reviewer decisions and timestamps (reviewer names are replaced by anonymous ordinals under
        blind mode), the record's conflict/consensus status, duplicate group id + primary flag, and — for validation
        studies — cross-validated (held-out) relevance columns. Existing columns never move; new ones are appended.
      </div>

      <ExportDialog open={!!expItem} onClose={() => setExpItem(null)} item={expItem} />
    </div>
  );
}
