/**
 * searchBuilderGoldCases.js — SB5 hand-authored gold cases for the Search Builder
 * intelligence benchmark. These are the harder, human-judged bar (the generated
 * corpus in searchBuilderCorpus.js supplies breadth). The EUS-biliary-drainage case
 * is the reference gold case from the SB5 spec.
 *
 * Each case: { caseId, reviewTitle, researchQuestion, pico:{P,I,C,O}, expected:{...},
 *   rejectNoise:[], notInPopulation:[], expectedDuplicates:[], expectedSynonyms:[], notes }
 *
 * `expected.*` lists the concept's KEY terms (the benchmark checks family-equivalence,
 * not exact strings, so "EUS" matches "endoscopic ultrasound"). Pure data; no I/O.
 */
export const GOLD_CASES = [
  {
    caseId: 'eus-biliary-drainage',
    reviewTitle: 'EUS-guided antegrade/transpapillary versus transluminal biliary drainage after failed ERCP in malignant biliary obstruction',
    researchQuestion: 'In patients with malignant biliary obstruction after failed ERCP, does EUS-guided antegrade/transpapillary biliary drainage compared with transluminal biliary drainage improve technical and clinical success?',
    pico: {
      P: 'patients with malignant biliary obstruction after failed ERCP',
      I: 'EUS-guided antegrade/transpapillary biliary drainage',
      C: 'EUS-guided transluminal biliary drainage',
      O: '',
    },
    expected: {
      population: ['malignant biliary obstruction'],
      intervention: ['EUS-guided antegrade biliary drainage', 'endoscopic ultrasound'],
      comparator: ['transluminal biliary drainage'],
      outcomes: [],
    },
    rejectNoise: ['failed', 'after', 'with', 'underwent', 'patients'],
    notInPopulation: ['endoscopic ultrasound', 'EUS', 'biliary drainage'],
    expectedDuplicates: [],
    expectedSynonyms: [['EUS', 'endoscopic ultrasound']],
    notes: 'The defining gold case. EUS/endoscopic ultrasound must classify to Intervention, never Population. Population is the disease (malignant biliary obstruction), not the procedure.',
  },
  {
    caseId: 'glp1-t2dm',
    reviewTitle: 'GLP-1 receptor agonists versus placebo in adults with type 2 diabetes',
    pico: { P: 'adults with type 2 diabetes', I: 'GLP-1 receptor agonists', C: 'placebo', O: 'HbA1c and weight loss' },
    expected: { population: ['type 2 diabetes'], intervention: ['GLP-1 receptor agonists'], comparator: ['placebo'], outcomes: ['weight loss'] },
    rejectNoise: ['adults', 'and', 'with'],
    notInPopulation: ['GLP-1 receptor agonists'],
    expectedSynonyms: [['T2DM', 'type 2 diabetes mellitus']],
    expectedVocab: ['Diabetes Mellitus, Type 2'],
    notes: 'Drug vs placebo. Drug must be Intervention, diabetes is Population. Diabetes MeSH must be the Type 2 heading, not a generic/wrong one.',
  },
  {
    caseId: 'af-ablation-stroke-outcome',
    reviewTitle: 'Catheter ablation versus antiarrhythmic drugs for atrial fibrillation',
    pico: { P: 'patients with atrial fibrillation', I: 'catheter ablation', C: 'antiarrhythmic drugs', O: 'stroke and mortality' },
    expected: { population: ['atrial fibrillation'], intervention: ['catheter ablation'], comparator: ['antiarrhythmic drugs'], outcomes: ['stroke', 'mortality'] },
    rejectNoise: ['patients', 'and'],
    notInPopulation: ['catheter ablation', 'stroke'],
    expectedVocab: ['Atrial Fibrillation'],
    notes: 'Critical ambiguity: stroke is an OUTCOME here, not the Population. Must NOT be relocated to Population.',
  },
  {
    caseId: 'stroke-thrombectomy',
    reviewTitle: 'Mechanical thrombectomy versus thrombolysis in acute ischemic stroke',
    pico: { P: 'adults with acute ischemic stroke', I: 'mechanical thrombectomy', C: 'intravenous thrombolysis', O: 'functional independence' },
    expected: { population: ['stroke'], intervention: ['mechanical thrombectomy'], comparator: ['intravenous thrombolysis'], outcomes: ['functional independence'] },
    rejectNoise: ['adults'],
    notInPopulation: ['mechanical thrombectomy'],
    notes: 'Mirror of the AF case: here stroke IS the Population. Term placement must respect context.',
  },
  {
    caseId: 'hcc-tace-sorafenib',
    reviewTitle: 'Transarterial chemoembolization versus sorafenib for hepatocellular carcinoma',
    pico: { P: 'hepatocellular carcinoma', I: 'transarterial chemoembolization', C: 'sorafenib', O: 'overall survival' },
    expected: { population: ['hepatocellular carcinoma'], intervention: ['transarterial chemoembolization'], comparator: ['sorafenib'], outcomes: ['mortality'] },
    rejectNoise: ['versus'],
    notInPopulation: ['transarterial chemoembolization', 'sorafenib'],
    expectedVocab: ['Carcinoma, Hepatocellular'],
    notes: 'Oncology procedure vs drug.',
  },
  {
    caseId: 'ibd-biologics',
    reviewTitle: 'Anti-TNF biologics versus placebo for moderate-to-severe ulcerative colitis',
    pico: { P: 'moderate to severe ulcerative colitis', I: 'anti-TNF biologics', C: 'placebo', O: 'clinical remission' },
    expected: { population: ['ulcerative colitis'], intervention: ['anti-TNF biologics'], comparator: ['placebo'], outcomes: ['clinical remission'] },
    rejectNoise: ['moderate', 'severe'],
    notInPopulation: ['anti-TNF biologics'],
    notes: 'IBD medication review.',
  },
  {
    caseId: 'copd-laba-lama',
    reviewTitle: 'LABA/LAMA versus LABA/ICS in COPD',
    pico: { P: 'patients with COPD', I: 'LABA-LAMA combination', C: 'LABA-ICS combination', O: 'exacerbations' },
    expected: { population: ['COPD'], intervention: ['LABA-LAMA combination'], comparator: ['LABA-ICS combination'], outcomes: ['exacerbations'] },
    rejectNoise: ['patients'],
    notInPopulation: ['LABA-LAMA combination'],
    notes: 'Pulmonology, two combination inhalers.',
  },
  {
    caseId: 'ckd-sglt2',
    reviewTitle: 'SGLT2 inhibitors versus placebo in chronic kidney disease',
    pico: { P: 'adults with chronic kidney disease', I: 'SGLT2 inhibitors', C: 'placebo', O: 'kidney disease progression' },
    expected: { population: ['chronic kidney disease'], intervention: ['SGLT2 inhibitors'], comparator: ['placebo'], outcomes: ['kidney disease progression'] },
    rejectNoise: ['adults'],
    notInPopulation: ['SGLT2 inhibitors'],
    notes: 'Nephrology drug vs placebo.',
  },
  {
    caseId: 'sepsis-balanced-fluids',
    reviewTitle: 'Balanced crystalloids versus saline in critically ill adults with sepsis',
    pico: { P: 'critically ill adults with sepsis', I: 'balanced crystalloids', C: 'normal saline', O: 'mortality and acute kidney injury' },
    expected: { population: ['sepsis'], intervention: ['balanced crystalloids'], comparator: ['normal saline'], outcomes: ['mortality', 'acute kidney injury'] },
    rejectNoise: ['critically', 'ill', 'adults'],
    notInPopulation: ['balanced crystalloids'],
    notes: 'Critical care; AKI is an outcome here, not the population.',
  },
  {
    caseId: 'colonoscopy-polyp-detection',
    reviewTitle: 'Artificial intelligence-assisted colonoscopy versus standard colonoscopy for adenoma detection',
    pico: { P: 'adults undergoing screening colonoscopy', I: 'AI-assisted colonoscopy', C: 'standard colonoscopy', O: 'adenoma detection rate' },
    expected: { population: ['screening colonoscopy'], intervention: ['AI-assisted colonoscopy'], comparator: ['standard colonoscopy'], outcomes: ['adenoma detection rate'] },
    rejectNoise: ['adults', 'undergoing'],
    notInPopulation: [],
    notes: 'Screening review; the population is defined by undergoing the procedure, so colonoscopy in Population is acceptable here.',
  },
  {
    caseId: 'bariatric-rygb-sleeve',
    reviewTitle: 'Roux-en-Y gastric bypass versus sleeve gastrectomy for severe obesity',
    pico: { P: 'adults with severe obesity', I: 'Roux-en-Y gastric bypass', C: 'sleeve gastrectomy', O: 'weight loss and diabetes remission' },
    expected: { population: ['obesity'], intervention: ['Roux-en-Y gastric bypass'], comparator: ['sleeve gastrectomy'], outcomes: ['weight loss'] },
    rejectNoise: ['adults', 'severe', 'and'],
    notInPopulation: ['Roux-en-Y gastric bypass'],
    notes: 'Bariatric surgery, procedure vs procedure.',
  },
  {
    caseId: 'dta-ddimer-pe',
    reviewTitle: 'D-dimer for diagnosis of suspected pulmonary embolism',
    pico: { P: 'patients with suspected pulmonary embolism', I: 'D-dimer testing', C: 'CT pulmonary angiography', O: 'diagnostic accuracy' },
    expected: { population: ['pulmonary embolism'], intervention: ['D-dimer testing'], comparator: ['CT pulmonary angiography'], outcomes: ['diagnostic accuracy'] },
    rejectNoise: ['patients', 'suspected'],
    notInPopulation: ['D-dimer testing'],
    notes: 'Diagnostic test accuracy review.',
  },
  {
    caseId: 'esd-emr-early-cancer',
    reviewTitle: 'Endoscopic submucosal dissection versus endoscopic mucosal resection for early gastric cancer',
    pico: { P: 'early gastric cancer', I: 'endoscopic submucosal dissection', C: 'endoscopic mucosal resection', O: 'en bloc resection' },
    expected: { population: ['gastric cancer'], intervention: ['endoscopic submucosal dissection'], comparator: ['endoscopic mucosal resection'], outcomes: ['en bloc resection'] },
    rejectNoise: ['early'],
    notInPopulation: ['endoscopic submucosal dissection', 'endoscopic mucosal resection'],
    expectedSynonyms: [['ESD', 'endoscopic submucosal dissection'], ['EMR', 'endoscopic mucosal resection']],
    notes: 'GI procedures; both procedures are intervention/comparator, not population.',
  },
  {
    caseId: 'hf-arni',
    reviewTitle: 'ARNI versus ACE inhibitors in heart failure with reduced ejection fraction',
    pico: { P: 'heart failure with reduced ejection fraction', I: 'sacubitril-valsartan', C: 'ACE inhibitors', O: 'cardiovascular mortality and hospitalization' },
    expected: { population: ['heart failure with reduced ejection fraction'], intervention: ['sacubitril-valsartan'], comparator: ['ACE inhibitors'], outcomes: ['mortality'] },
    rejectNoise: ['and'],
    notInPopulation: ['sacubitril-valsartan'],
    notes: 'HFrEF must stay one phrase, not fragment into heart/reduced/ejection/fraction.',
  },
  {
    caseId: 'htn-spironolactone',
    reviewTitle: 'Spironolactone for resistant hypertension',
    pico: { P: 'adults with resistant hypertension', I: 'spironolactone', C: 'placebo', O: 'blood pressure' },
    expected: { population: ['hypertension'], intervention: ['spironolactone'], comparator: ['placebo'], outcomes: ['blood pressure'] },
    rejectNoise: ['adults', 'resistant'],
    notInPopulation: ['spironolactone'],
    notes: 'Cardiology/endocrine drug review.',
  },
  {
    caseId: 'crc-screening',
    reviewTitle: 'FIT versus colonoscopy for colorectal cancer screening',
    pico: { P: 'average-risk adults', I: 'fecal immunochemical test', C: 'colonoscopy', O: 'colorectal cancer incidence and mortality' },
    expected: { population: ['average-risk adults'], intervention: ['fecal immunochemical test'], comparator: ['colonoscopy'], outcomes: ['colorectal cancer', 'mortality'] },
    rejectNoise: ['adults', 'and'],
    notInPopulation: ['fecal immunochemical test'],
    notes: 'Screening review; colorectal cancer is an OUTCOME (incidence), population is average-risk adults.',
  },
  {
    caseId: 'nafld-resmetirom',
    reviewTitle: 'Resmetirom versus placebo in non-alcoholic fatty liver disease',
    pico: { P: 'non-alcoholic fatty liver disease', I: 'resmetirom', C: 'placebo', O: 'NASH resolution' },
    expected: { population: ['non-alcoholic fatty liver disease'], intervention: ['resmetirom'], comparator: ['placebo'], outcomes: ['NASH resolution'] },
    rejectNoise: [],
    notInPopulation: ['resmetirom'],
    notes: 'Hepatology drug vs placebo.',
  },
  {
    caseId: 'crohn-ustekinumab',
    reviewTitle: 'Ustekinumab versus adalimumab for Crohn disease',
    pico: { P: "Crohn's disease", I: 'ustekinumab', C: 'adalimumab', O: 'clinical remission' },
    expected: { population: ["Crohn's disease"], intervention: ['ustekinumab'], comparator: ['adalimumab'], outcomes: ['clinical remission'] },
    rejectNoise: [],
    notInPopulation: ['ustekinumab'],
    notes: 'IBD biologic head-to-head.',
  },
  {
    caseId: 'mi-ticagrelor',
    reviewTitle: 'Ticagrelor versus clopidogrel after myocardial infarction',
    pico: { P: 'patients with myocardial infarction', I: 'ticagrelor', C: 'clopidogrel', O: 'major adverse cardiovascular events' },
    expected: { population: ['myocardial infarction'], intervention: ['ticagrelor'], comparator: ['clopidogrel'], outcomes: ['major adverse cardiovascular events'] },
    rejectNoise: ['patients'],
    notInPopulation: ['ticagrelor'],
    notes: 'Cardiology antiplatelet.',
  },
  {
    caseId: 'tb-regimen',
    reviewTitle: 'Four-month rifapentine-based regimen versus standard six-month regimen for drug-susceptible tuberculosis',
    pico: { P: 'adults with drug-susceptible pulmonary tuberculosis', I: 'four-month rifapentine regimen', C: 'standard six-month regimen', O: 'treatment success and relapse' },
    expected: { population: ['tuberculosis'], intervention: ['rifapentine regimen'], comparator: ['six-month regimen'], outcomes: ['treatment success'] },
    rejectNoise: ['adults'],
    notInPopulation: [],
    notes: 'Infectious disease; non-inferiority regimen comparison.',
  },
  {
    caseId: 'covid-antiviral',
    reviewTitle: 'Nirmatrelvir-ritonavir versus placebo in non-hospitalized COVID-19',
    pico: { P: 'non-hospitalized adults with COVID-19', I: 'nirmatrelvir-ritonavir', C: 'placebo', O: 'hospitalization or death' },
    expected: { population: ['COVID-19'], intervention: ['nirmatrelvir-ritonavir'], comparator: ['placebo'], outcomes: ['hospitalization'] },
    rejectNoise: ['adults', 'or'],
    notInPopulation: ['nirmatrelvir-ritonavir'],
    notes: 'Infectious disease antiviral.',
  },
  {
    caseId: 'aki-rrt-timing',
    reviewTitle: 'Early versus standard initiation of renal replacement therapy in acute kidney injury',
    pico: { P: 'critically ill patients with acute kidney injury', I: 'early renal replacement therapy', C: 'standard renal replacement therapy', O: 'mortality' },
    expected: { population: ['acute kidney injury'], intervention: ['early renal replacement therapy'], comparator: ['standard renal replacement therapy'], outcomes: ['mortality'] },
    rejectNoise: ['critically', 'ill', 'patients'],
    notInPopulation: ['early renal replacement therapy'],
    notes: 'Nephrology/critical care timing comparison; AKI is the population here.',
  },
  {
    caseId: 'asthma-biologics',
    reviewTitle: 'Anti-IL5 biologics for severe eosinophilic asthma',
    pico: { P: 'severe eosinophilic asthma', I: 'anti-IL5 biologics', C: 'placebo', O: 'exacerbations' },
    expected: { population: ['asthma'], intervention: ['anti-IL5 biologics'], comparator: ['placebo'], outcomes: ['exacerbations'] },
    rejectNoise: ['severe'],
    notInPopulation: ['anti-IL5 biologics'],
    notes: 'Pulmonology biologics.',
  },
  {
    caseId: 'prognosis-frailty',
    reviewTitle: 'Frailty as a prognostic factor for mortality after cardiac surgery',
    pico: { P: 'adults undergoing cardiac surgery', I: 'frailty', C: 'no frailty', O: 'postoperative mortality' },
    expected: { population: ['cardiac surgery'], intervention: ['frailty'], comparator: [], outcomes: ['mortality'] },
    rejectNoise: ['adults', 'undergoing'],
    notInPopulation: [],
    notes: 'Prognosis review; the "exposure" is frailty, the outcome is mortality.',
  },
  {
    caseId: 'exposure-pm25',
    reviewTitle: 'Long-term exposure to PM2.5 and risk of lung cancer',
    pico: { P: 'general population', I: 'PM2.5 exposure', C: '', O: 'lung cancer' },
    expected: { population: [], intervention: ['PM2.5 exposure'], comparator: [], outcomes: ['lung cancer'] },
    rejectNoise: [],
    notInPopulation: [],
    notes: 'Environmental exposure/risk-factor review; lung cancer is the outcome. Population is a general population (no specific disease concept asserted).',
  },
  {
    caseId: 'cirrhosis-tips',
    reviewTitle: 'TIPS versus endoscopic band ligation for prevention of variceal rebleeding in cirrhosis',
    pico: { P: 'patients with cirrhosis and variceal bleeding', I: 'transjugular intrahepatic portosystemic shunt', C: 'endoscopic band ligation', O: 'rebleeding and hepatic encephalopathy' },
    expected: { population: ['cirrhosis'], intervention: ['transjugular intrahepatic portosystemic shunt'], comparator: ['endoscopic band ligation'], outcomes: ['rebleeding'] },
    rejectNoise: ['patients', 'and'],
    notInPopulation: ['transjugular intrahepatic portosystemic shunt'],
    notes: 'Hepatology procedure vs procedure.',
  },
  {
    caseId: 'noninferiority-doac',
    reviewTitle: 'DOACs versus warfarin for stroke prevention in atrial fibrillation',
    pico: { P: 'patients with non-valvular atrial fibrillation', I: 'direct oral anticoagulants', C: 'warfarin', O: 'stroke and major bleeding' },
    expected: { population: ['atrial fibrillation'], intervention: ['direct oral anticoagulants'], comparator: ['warfarin'], outcomes: ['stroke', 'major bleeding'] },
    rejectNoise: ['patients'],
    notInPopulation: ['direct oral anticoagulants', 'stroke'],
    notes: 'Comparative effectiveness; stroke is the outcome, AF is the population.',
  },
  {
    caseId: 'ercp-failed-pop',
    reviewTitle: 'EUS-guided biliary drainage after failed ERCP for distal malignant biliary obstruction',
    pico: { P: 'distal malignant biliary obstruction after failed ERCP', I: 'EUS-guided biliary drainage', C: 'percutaneous transhepatic biliary drainage', O: 'technical success and adverse events' },
    expected: { population: ['malignant biliary obstruction'], intervention: ['EUS-guided biliary drainage'], comparator: ['percutaneous transhepatic biliary drainage'], outcomes: ['technical success', 'adverse events'] },
    rejectNoise: ['failed', 'after'],
    notInPopulation: ['EUS-guided biliary drainage', 'endoscopic ultrasound'],
    expectedSynonyms: [['ERCP', 'endoscopic retrograde cholangiopancreatography']],
    notes: 'Second EUS case; reinforces procedure-not-in-population and ERCP acronym expansion.',
  },
];

export default GOLD_CASES;
